from flask import Blueprint, send_from_directory, current_app

statistics_bp = Blueprint('statistics', __name__, url_prefix='/statistics')

@statistics_bp.route('/')
def statistics():
    # Serve the pre-rendered static HTML file generated by your Celery task
    return send_from_directory(current_app.static_folder, 'statistics.html')
